#!/bin/bash

function GetInfo
{
    echo "<Plugins"
    echo "  Author = \"Bruno Adele\""
    echo "  Email = \"b_adele@netcourrier.com\""
    echo "  Title = \"Ftp overflow\""
    echo "  Version = \"1.0\""
    echo "  Type = \"Dianostic\""
    echo "  Info = \"teste les debordement memoire\""
    echo "  Web = \"http://www.jesuislibre.org\""
    echo "  Options = \"Ftp_Port = 21\""
    echo "  Solution = \"\""
    echo "/>"
}

function Start
{
   if [ "$1" == "getinfo" ] ; then
        GetInfo
    else 
	InitParam $1 $2
	CheckParam
	Execute
	CleanResultat
	ShowResultat
    fi
}

function InitParam
{
    ADDRESSE=$1
    PORT=$2
}

function CheckParam
{
    if [ "$PORT" == "" ] ; then
        PORT="80"
    fi
}     

function Execute
{
    RESULTAT=`lynx http://$ADDRESSE:$PORT --mime-header  | egrep '^Server:'`
}

function CleanResultat
{
    RESULTAT=`echo $RESULTAT | sed -e "s/Server://"`
}

function ShowResultat
{
    if [ "$RESULTAT" != "" ]  ; then
        echo "Resultat: $RESULTAT" 
    fi    
}



Start $1 $2




